Update node.js.yml

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -11,23 +11,30 @@ on:
 
 jobs:
   build:
-
     runs-on: ubuntu-latest
 
-    #strategy:
-      #matrix:
-        #node-version: [ 20.17.0 ]
-        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
-
     steps:
-    - working-directory: ./mouse-frontend-app
     - uses: actions/checkout@v4
-    - name: Use Node.js 20.17.0 #${{ matrix.node-version }}
+    - name: Use Node.js 20.17.0
       uses: actions/setup-node@v4
       with:
-        node-version: 20.17.0 #${{ matrix.node-version }}
+        node-version: 20.17.0
         cache: 'npm'
-        cache-dependency-path: subdir/package-lock.json    
-    - run: npm ci
-    - run: npm run build --if-present
-    - run: npm test
+        cache-dependency-path: ./mouse-frontend-app/package-lock.json
+    - run: |
+        cd ./mouse-frontend-app
+        npm ci
+    - run: |
+        cd ./mouse-frontend-app
+        npm run build --if-present   
+        
+    - name: Run ESLint
+      working-directory: ./mouse-frontend-app
+      run: npm run lint
+      continue-on-error: false
+        
+    - name: Fail if any previous step failed
+      if: ${{ failure() }}
+      run: |
+        echo "An error occurred during the build process. Aborting push."
+        exit 1
