Update node.js.yml

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -26,4 +26,10 @@ jobs:
         npm ci
     - run: |
         cd ./mouse-frontend-app
-        npm run build --if-present    
+        npm run build --if-present   
+        
+    - name: Fail if any previous step failed
+      if: ${{ failure() }}
+      run: |
+        echo "An error occurred during the build process. Aborting push."
+        exit 1
